# Site settings
title: cryptopocalyp.se
# email: zaprice@cryptopocalyp.se
gmail: zprice11@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Zach Price personal site.
copyright: >
  Copyright <i class="fa fa-copyright"></i> 2018 Zachary Price</br>
  <a href=https://www.gnu.org/licenses/gpl-2.0.html>
  GNU GPL v2</a> ALL WRONGS RESERVED</br>
  Source code can be found
  <a href=https://github.com/zaprice/cryptopocalyp.se>
  here</a>.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://cryptopocalyp.se" # the base hostname & protocol for your site
twitter_username: mightbeprime
github_username:  zaprice
pinboard_username: zaprice
timezone: US/Eastern

public_key: "/assets/zprice11_public_key.txt"
JPS: "/assets/JPS1.pdf"

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  math_engine: null
