# Site settings
title: THE END IS NEAR
email: zaprice@cryptocalyp.se
description: > # this means to ignore newlines until "baseurl:"
  Zach Price personal site.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cryptocalyp.se" # the base hostname & protocol for your site
twitter_username: mightbeprime
github_username:  zaprice
pinboard_username: zaprice
timezone: US/Eastern

# Build settings
markdown: kramdown
highlighter: rouge
